### ISSUE TITLE
"sc qdescription MsQuic" fails

### ISSUE THREAD

**Issue by skissane** [microsoft/msquic#1240] opened 2021-02-16 19:22 UTC
### Describe the bug
"sc qdescription MsQuic" fails with error:
```
[SC] QueryServiceConfig2 FAILED 15100:

The resource loader failed to find MUI file.
```

This is the only driver on my system for which `sc qdescription` fails with this particular error. Most of the drivers, it successfully returns a description string – very often blank, but sometimes not. (There are a couple of other drivers for which `sc qdescription` fails, albeit with some other error code – it fails for both `vhdparser` and `pvhdparser` with error code 1168 (Element not found) – however, I assume issues with those two drivers are not on-topic for this GitHub project.)

I am running Windows 10 Version 2004 (OS Build 19041.804).

### Steps to reproduce the behavior

1. Run `sc qdescription MsQuic`
2. View output
3. See error

### Expected vs actual behavior

There should be no error. Ideally it would return a meaningful description of the MsQuic driver. But even a blank string would be better than an error.

**Comment by ThadHouse** [comment] 2021-02-16 20:01
Since 2004 doesn't include msquic inbox, the missing mui failure makes sense. However, even on an inbox build, I get the following error.

```
[SC] QueryServiceConfig2 FAILED 1814:

The specified resource name cannot be found in the image file.
```

I'll have to investigate why, and exactly which resource field that seems to be using.

**Comment by nibanks** [comment] 2021-02-16 20:06
I believe this is because we don't localize (and therefore generate a .mui) msquic strings.

**Comment by thhous-msft** [comment] 2021-08-23 16:38
We found out what was causing this to be broken. The issue is in windows however, so it can't be fixed without a new windows release. However, in future versions this will be fixed.

**Closed by thhous-msft** 2021-08-23 16:38 UTC
Labels: OS: Windows (Kernel), external
