### ISSUE TITLE
Crash in msquic!QuicConnUninitialize

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#499] opened 2020-06-12 03:24 UTC
### Describe the bug

```
==================================================================================
 msquictest.exe.6692.dmp
==================================================================================
 # Child-SP          RetAddr           Call Site
00 000000ac`ed5fdb78 00007ff8`b1e2ca8e ntdll!ZwWaitForMultipleObjects+0x14
01 000000ac`ed5fdb80 00007ff8`b1e2c97e KERNELBASE!WaitForMultipleObjectsEx+0xfe
02 000000ac`ed5fde80 00007ff8`b4527acf KERNELBASE!WaitForMultipleObjects+0xe
03 000000ac`ed5fdec0 00007ff8`b452757c kernel32!WerpLaunchAeDebug+0x285f
04 000000ac`ed5fdfe0 00007ff8`b1e5719e kernel32!WerpLaunchAeDebug+0x230c
05 000000ac`ed5fe020 00007ff8`b531820b KERNELBASE!UnhandledExceptionFilter+0x35e
06 000000ac`ed5fe130 00007ff8`b52ffd56 ntdll!memset+0x1c8b
07 000000ac`ed5fe170 00007ff8`b531479f ntdll!_C_specific_handler+0x96
08 000000ac`ed5fe1e0 00007ff8`b5274bef ntdll!_chkstk+0x11f
09 000000ac`ed5fe210 00007ff8`b531350e ntdll!RtlWalkFrameChain+0x14bf
0a 000000ac`ed5fe940 00007ff8`798ccedb ntdll!KiUserExceptionDispatcher+0x2e
*** WARNING: Unable to verify checksum for msquic.dll
0b 000000ac`ed5ff050 00007ff8`799568ba msquic!QuicListEntryRemove+0x2b
0c 000000ac`ed5ff0a0 00007ff8`79905101 msquic!QuicHashtableRemove+0x11a
0d 000000ac`ed5ff0f0 00007ff8`79903f29 msquic!QuicLookupRemoveLocalCidInt+0x241
0e 000000ac`ed5ff160 00007ff8`798d10f5 msquic!QuicLookupRemoveLocalCids+0x89
0f 000000ac`ed5ff1b0 00007ff8`798efa6f msquic!QuicBindingRemoveConnection+0x65
10 000000ac`ed5ff1e0 00007ff8`798e87a3 msquic!QuicConnUninitialize+0x13f
11 000000ac`ed5ff230 00007ff8`798e3c2f msquic!QuicConnDrainOperations+0x5c3
12 000000ac`ed5ff4d0 00007ff8`798e29b7 msquic!QuicWorkerProcessConnection+0x24f
13 000000ac`ed5ff790 00007ff8`b44d7974 msquic!QuicWorkerThread+0xd7
14 000000ac`ed5ffa30 00007ff8`b52da271 kernel32!BaseThreadInitThunk+0x14
15 000000ac`ed5ffa60 00000000`00000000 ntdll!RtlUserThreadStart+0x21
==================================================================================
```
This crash was encountered during a routine CI run (Windows-mitls: AppData/WithSend0RttArgs1.Send0Rtt/93):
https://dev.azure.com/ms/msquic/_build/results?buildId=87368&view=logs&j=824a454a-a391-5c10-4b27-1797b2064853&t=401d5336-0fa7-5e96-5956-a5f4353c7c92

**Comment by ThadHouse** [comment] 2020-08-04 23:17
Have we seen this again recently? I know we made some changes to the CID stuff.

**Comment by nibanks** [comment] 2020-08-04 23:19
I'm not sure if it's hit recently. But I also don't know of any change that would have fixed this kind of crash.

**Comment by ThadHouse** [comment] 2020-08-28 20:07
This has not been reproduced since the last report, and the logs have been deleted from AZP. There has been some minor changes in this area. Closing, will reopen if seen again.

**Closed by ThadHouse** 2020-08-28 20:07 UTC
Labels: Area: Core, bug
