### ISSUE TITLE
Perf Pipeline Issues

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1312] opened 2021-03-05 17:09 UTC
### Describe the bug

A few problems I found with the Perf CI pipeline today:

- Collecting CPU traces of the client doesn't seem to work. Server side works fine. I can open the ETL in WPA and see what I need. It just seems to be missing for client.
- A PGO run failed (see [here](https://dev.azure.com/ms/msquic/_build/results?buildId=145102&view=logs&j=8983645b-cb98-5eb1-53b9-2f71d06ab3f1&t=7355488f-29fd-5857-ff0e-654f0dbbef3c)).

**Comment by ThadHouse** [comment] 2021-03-12 21:41
PGO failures were caused by MSVC runtime being out of date. Will investigate client CPU traces

**Comment by ThadHouse** [comment] 2021-03-12 22:26
I can't reproduce the client issue. Running it currently it works just fine. So closing, we can reopen if its seen again.

**Closed by ThadHouse** 2021-03-12 22:26 UTC
Labels: Area: Performance, Area: Pipeline
