### ISSUE TITLE
MsQuic does not build on Fedora35

### ISSUE THREAD

**Issue by wfurt** [microsoft/msquic#1851] opened 2021-07-25 02:59 UTC
I don't know if that is new clang-12 or if there some something suspicious about the lltng headers. 

```
In file included from /usr/include/lttng/tracepoint.h:39,
                 from /msquic/src/msquic/build/linux/x64_openssl/inc/core.clog/operation.h.clog.h:10,
                 from /msquic/src/msquic/src/core/operation.h:9,
                 from /msquic/src/msquic/src/core/precomp.h:55,
                 from /msquic/src/msquic/src/core/connection.c:34:
/msquic/src/msquic/src/core/connection.c: In function ‘QuicConnOnShutdownComplete’:
/msquic/src/msquic/build/linux/x64_openssl/inc/core.clog/connection.c.clog.h:2408:1: error: ‘typeof’ applied to a bit-field
 2408 | tracepoint(CLOG_CONNECTION_C, ConnShutdownComplete , arg2, arg3);\
      | ^~~~~~~~~~
/msquic/src/msquic/build/linux/x64_openssl/clog/clog.h:73:32: note: in expansion of macro ‘_clog_4_ARGS_TRACE_ConnShutdownComplete’
   73 | #define _clog_CAT_HELPER(x, y) x ## y
```

I've got this when trying to get .NET testing container. As mitigation I'm building with `-DisableLogs`. 

cc: @omajid

**Comment by thhous-msft** [comment] 2021-07-26 22:34
It looks like whats happening here is LTTng uses typeof on variables to correctly log. However, you can't do typeof on a bitfield. Just to double check, are you sure this is using clang and not some old version of GCC. And also exactly which version of clang?

**Comment by wfurt** [comment] 2021-07-26 22:44
clang-12. I hit this while working on https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/483 e.g. default RedHat container (registry.fedoraproject.org/fedora:34). I did try gcc as well as fallback e.g. CC=gcc before running build but that did not work either.

**Comment by thhous-msft** [comment] 2021-07-26 22:49
Interesting. I wonder if its a different version of lttng. What version of lttng does that image have through its package manager?

**Comment by omajid** [comment] 2021-07-26 22:58
```
$ podman run -it registry.fedoraproject.org/fedora:34 dnf info -q lttng-ust

Name         : lttng-ust
Version      : 2.12.0
Release      : 4.fc34
Architecture : x86_64
Size         : 289 k
Source       : lttng-ust-2.12.0-4.fc34.src.rpm
Repository   : fedora
Summary      : LTTng Userspace Tracer library
URL          : https://lttng.org
License      : LGPLv2.1, MIT and GPLv2
Description  : This library may be used by user-space applications to generate
             : trace-points using LTTng.
```

**Comment by wfurt** [comment] 2021-07-26 22:58
lttng-ust-devel-2.12.0-4.fc34.x86_64

**Comment by thhous-msft** [comment] 2021-07-26 22:59
Ok. Thats the same version we use. So thats definitely interesting thats failing on fedora. We'll take a look at some time. But at least for now you have a workaround.

**Comment by omajid** [comment] 2021-07-26 23:10
Fedora compiles lttng-ust like this:

```
autoreconf -vif

%configure \
  --docdir=%{_docdir}/%{name} \
  --disable-static \
  --enable-python-agent \
  --with-sdt \
  %{?arg_numactl}

make %{?_smp_mflags} V=1
```

Which evaluates to something like this:

```
# Reinitialize libtool with the fedora version to remove Rpath                                                          
autoreconf -vif                                                                                                         
                                                                                                                        
                                                                                                                        
                                                                                                                        
  CFLAGS="${CFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-se
curity -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protecto
r-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-
protection -fcf-protection}" ; export CFLAGS ;                                                                          
  CXXFLAGS="${CXXFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=forma
t-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-prot
ector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-cl
ash-protection -fcf-protection}" ; export CXXFLAGS ;                                                                    
  FFLAGS="${FFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-se
curity -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protecto
r-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-
protection -fcf-protection -I/usr/lib64/gfortran/modules}" ; export FFLAGS ;                                            
  FCFLAGS="${FCFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-
security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protec
tor-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clas
h-protection -fcf-protection -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ;                                         
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld }" ; export
 LDFLAGS ;                                                                                                              
  LT_SYS_LIBRARY_PATH="${LT_SYS_LIBRARY_PATH:-/usr/lib64:}" ; export LT_SYS_LIBRARY_PATH ;                              
  CC="${CC:-gcc}" ; export CC ;                                                                                         
  CXX="${CXX:-g++}" ; export CXX;                                                                                       
  [ "-flto=auto -ffat-lto-objects"x != x ] &&                                                                           
  for file in $(find . -type f -name configure -print); do                                                              
    /usr/bin/sed -r --in-place=.backup 's/^char \(\*f\) \(\) = /__attribute__ ((used)) char (*f) () = /g' $file;        
    diff -u $file.backup $file && mv $file.backup $file     
    /usr/bin/sed -r --in-place=.backup 's/^char \(\*f\) \(\);/__attribute__ ((used)) char (*f) ();/g' $file;            
    diff -u $file.backup $file && mv $file.backup $file                                                                 
    /usr/bin/sed -r --in-place=.backup 's/^char \$2 \(\);/__attribute__ ((used)) char \$2 ();/g' $file;                 
    diff -u $file.backup $file && mv $file.backup $file                                                                 
    /usr/bin/sed --in-place=.backup '1{$!N;$!N};$!N;s/int x = 1;\nint y = 0;\nint z;\nint nan;/volatile int x = 1; volat
ile int y = 0; volatile int z, nan;/;P;D' $file;                                                                        
    diff -u $file.backup $file && mv $file.backup $file                                                                 
    /usr/bin/sed --in-place=.backup 's#^lt_cv_sys_global_symbol_to_cdecl=.*#lt_cv_sys_global_symbol_to_cdecl="sed -n -e 
'"'"'s/^T .* \\(.*\\)$/extern int \\1();/p'"'"' -e '"'"'s/^$symcode* .* \\(.*\\)$/extern char \\1;/p'"'"'"#' $file;     
    diff -u $file.backup $file && mv $file.backup $file                                                                 
  done;                                                                                                                 
  [ "1" = 1 ] && for i in $(find $(dirname ./configure) -name config.guess -o -name config.sub) ; do                    
      [ -f /usr/lib/rpm/redhat/$(basename $i) ] && /usr/bin/rm -f $i && /usr/bin/cp -fv /usr/lib/rpm/redhat/$(basename $
i) $i ;                                                                                                                 
  done ;                                                                                                                
  [ "1" = 1 ] && [ x != "x-Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld" ] &&                                
      for i in $(find . -name ltmain.sh) ; do                                                                           
        /usr/bin/sed -i.backup -e 's~compiler_flags=$~compiler_flags="-Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-harde
ned-ld"~' $i                                                                                                            
      done ;                                              
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \                                          
        --program-prefix= \                                                                                             
        --disable-dependency-tracking \                                                                                 
         \                                                                                                              
        --prefix=/usr \                                                                                                 
        --exec-prefix=/usr \                                                                                            
        --bindir=/usr/bin \                                                                                             
        --sbindir=/usr/sbin \                               
        --sysconfdir=/etc \                                                                                             
        --datadir=/usr/share \                                                                                          
        --includedir=/usr/include \                                                                                     
        --libdir=/usr/lib64 \                                                                                           
        --libexecdir=/usr/libexec \                                                                                     
        --localstatedir=/var \                                                                                          
        --sharedstatedir=/var/lib \                                                                                     
        --mandir=/usr/share/man \                                                                                       
        --infodir=/usr/share/info \                                                                                     
        --docdir=/usr/share/doc/lttng-ust \                                                                             
        --disable-static \                                                                                              
        --enable-python-agent \                                                                                         
        --with-sdt \                                                                                                    
        --enable-numa                                                                                                   
                                                                                                                        
make -j8 V=1                            
```

Don't know if that helps to reproduce the issue. The `--with-sdt` flag, in particular, looks different from [what Debian does to build it](https://salsa.debian.org/debian/ust/-/blob/debian/sid/debian/rules).

**Comment by thhous-msft** [comment] 2021-07-26 23:12
I would suspect it is related to sdt.

https://lists.lttng.org/pipermail/lttng-dev/2015-June/024601.html

This issue shows the same error occuring when lttng is built with sdt integration. That would explain why we never saw this before.

**Comment by thhous-msft** [comment] 2021-07-29 16:57
Just doing some investigation to see if we can disable sdt support when we build our binaries, even if lttng was configured with it. I don't have an easy way to set up linux containers, but can someone post the contents of `ust-config.h` from that fedora build? It should be in `/usr/include/lttng`

**Comment by omajid** [comment] 2021-07-29 20:59
From my Fedora 34 machine:

```
$ cat /usr/include/lttng/ust-config.h 
/* include/lttng/ust-config.h.  Generated from ust-config.h.in by configure.  */
/* ust/config.h.in. Manually generated for control over the contained defs. */

/* Use efficient unaligned access. */
#define LTTNG_UST_HAVE_EFFICIENT_UNALIGNED_ACCESS 1

/* DTrace/GDB/SystemTap integration via sdt.h */
#define LTTNG_UST_HAVE_SDT_INTEGRATION 1

/* Perf event integration via perf_event.h */
#define LTTNG_UST_HAVE_PERF_EVENT 1
```

And Fedora 35, using docker:

```
$ podman run -it registry.fedoraproject.org/fedora:rawhide bash -c 'sudo dnf install -yq lttng-ust-devel && echo '-----' && cat /usr/include/lttng/ust-config.h'

Installed:
  libpkgconf-1.8.0-1.fc35.x86_64                                       lttng-ust-2.12.2-5.fc35.x86_64                 
  lttng-ust-devel-2.12.2-5.fc35.x86_64                                 numactl-libs-2.0.14-4.fc35.x86_64              
  pkgconf-1.8.0-1.fc35.x86_64                                          pkgconf-m4-1.8.0-1.fc35.noarch                 
  pkgconf-pkg-config-1.8.0-1.fc35.x86_64                               python3-pyparsing-2.4.7-9.fc35.noarch          
  systemtap-sdt-devel-4.6~pre16262021g84ef6bd9-2.fc35.x86_64           userspace-rcu-0.13.0-3.fc35.x86_64             
  userspace-rcu-devel-0.13.0-3.fc35.x86_64                            

-----
/* include/lttng/ust-config.h.  Generated from ust-config.h.in by configure.  */
/* ust/config.h.in. Manually generated for control over the contained defs. */

/* Use efficient unaligned access. */
#define LTTNG_UST_HAVE_EFFICIENT_UNALIGNED_ACCESS 1

/* DTrace/GDB/SystemTap integration via sdt.h */
#define LTTNG_UST_HAVE_SDT_INTEGRATION 1

/* Perf event integration via perf_event.h */
#define LTTNG_UST_HAVE_PERF_EVENT 1

```

**Comment by thhous-msft** [comment] 2021-07-29 21:00
@wfurt sent them to me. Because `LTTNG_UST_HAVE_SDT_INTEGRATION` is an unconditional define, theres nothing we're going to be able to do from our end to fix this other than just disabling logs. We use bit fields all over the place, so fixing this at the source code level would be a very large change.

**Comment by thhous-msft** [comment] 2021-08-04 18:02
https://github.com/microsoft/msquic/pull/1876 now checks if that variable is defined, and if so will spit out a warning in cmake and disable logging. I'll try to get a fedora build and test it out just to double check.

**Comment by thhous-msft** [comment] 2021-08-06 18:52
@wfurt @omajid I don't think there's anything actionable we can do here. The build will now automatically disable logging if SDT is enabled in lttng. I did a double check to see if there was another way to disable SDT support at build time, and there was not. So I'm going to close this unless we can come up with some other way to fix this.

**Closed by thhous-msft** 2021-08-06 18:52 UTC
Labels: Area: Build
