### ISSUE TITLE
Memory leak in msquic 1.0.4

### ISSUE THREAD

**Issue by Nuklon** [microsoft/msquic#2658] opened 2022-04-24 08:46 UTC
### Describe the bug

Since running this new version, I've had to restart the server twice due to memory getting to 100%. I've looked into it with poolmon and one tag uses ~32GB of RAM:

```
 Memory:67018228K Avail:  270612K  PageFlts:  9355   InRam Krnl:47756K P:390536K
 Commit:72832896K Limit:84635012K Peak:80802964K            Pool N:37417736K P:635236K
 System pool information
 Tag  Type     Allocs            Frees            Diff       Bytes                  Per Alloc

 Qc1A Nonp   92404489 (   0)      6827 (   0) 92397662 34002339616 (          0)         368
```
Sorry for bad formatting, I couldn't get this formatted correctly. Here's the screenshot:

![image](https://user-images.githubusercontent.com/23340481/164915249-04b2f54b-cca8-4fbd-89ad-7c6eec83b2f4.png)

Since the server worked correctly before without any problems, I suspected it was due to msquic, and looking at the code it seems this tag is indeed used by msquic:
https://github.com/microsoft/msquic/blob/main/src/inc/quic_platform.h#L96

I do not have a memory dump. I tried creating one with notmyfault but the server crashed/rebooted immediately without writing any dump, and I have since disabled quic in IIS again.

My setup is still the same, ASP.NET Core 6.0, IIS, WS2022 latest updates. I have also disabled legacy TLS on most sites.

Originally posted here: https://github.com/microsoft/msquic/issues/2249#issuecomment-1107534912

### Affected OS

- [ ] All
- [X] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

release/1.0

### Steps taken to reproduce bug

Runs on production server, encountered it twice.

### Expected behavior

Shouldn't leak memory.

### Actual outcome

Memory getting filled to 100%.

### Additional details

ASP.NET Core 6.0, IIS, WS2022

NIC: Intel(R) I210 Gigabit.
Driver: 12.18.12.1 from 23-2-2021.

**Comment by thhous-msft** [comment] 2022-04-24 16:27
Just to double check, were you running MsQuic/HTTP3 before, and this is new behavior as of the latest patch, or is this the first time using MsQuic on your server? Just to make regression testing slightly easier.

**Comment by Nuklon** [comment] 2022-04-24 18:13
> Just to double check, were you running MsQuic/HTTP3 before, and this is new behavior as of the latest patch, or is this the first time using MsQuic on your server? Just to make regression testing slightly easier.

I did try it a couple of times, but due to bug #2249 / #2188 I disabled Quic in IIS as it would BSOD about 2-3 times a day. I don't recall memory being filled up like this, but I don't think it ever got that far because of the BSOD. In about a week I now had to reboot twice, so 2-3 days to fill whatever memory was left.

**Comment by Nuklon** [comment] 2022-04-26 09:40
I've tried the driver (12.18.9.7) from Intel that shipped with the motherboard and I'm seeing similar behavior. I've only enabled quic for one site and the driver memory usage now increases about ~800MB / day.

**Comment by thhous-msft** [comment] 2022-04-26 16:02
Would you be able to grab some logs on that system? 

https://github.com/microsoft/msquic/blob/f7f41159437f187e1d8e40430ef54eca97f80450/docs/Diagnostics.md

With that much leaking, I would expect only a minute or so of logs would be necessary, as thats about 1500 leaks a seconds.

**Comment by Nuklon** [comment] 2022-04-26 16:50
Yes, of course. I used ```netsh.exe trace start overwrite=yes report=dis correlation=dis traceFile=quic.etl provider={ff15e657-4f26-570e-88ab-0796b258d11c} level=0x5 keywords=0xffffffff``` for a couple of minutes. I don't really use ETW, so if there's another command you'd like to run, please let me know. I've been monitoring the memory usage with poolmon the last couple of hours hours and sometimes it's unchanged for 30-60 mins. I have not found a pattern in this, and I don't know if the problem is visible in this file, I can do some new traces again if needed.
[quic.zip](https://github.com/microsoft/msquic/files/8565221/quic.zip)

**Comment by thhous-msft** [comment] 2022-04-27 17:29
Can you grab UDP logs as well? You're right that log doesn't show anything, we don't log every completion, only when it has a bad status. UDP logs might show if there if we're not getting completions from the network stack.

netsh trace start scenario=InternetServer_dbg provider=Microsoft-Windows-TCPIP level=5 capture=yes packettruncatebytes=120 tracefile=net.etl report=disabled perf=no correlation=disabled

**Comment by Nuklon** [comment] 2022-04-28 09:09
This went massive real quick, so the trace didn't run that long. 
[net.zip](https://github.com/microsoft/msquic/files/8581288/net.zip)

Is there any filtering possible for quic / nec to perhaps reduce this to more or less useful entries?

**Comment by webwizuk** [comment] 2022-05-09 07:40
This is the exact same error I have been getting with Windows Server 2022 running IIS since it was launched last August with the "Qc1A Nonp" memory leak that uses up all available memory.

I have over 20 web servers running Windows Server 2022 IIS 10 running as virtual servers on Windows 2019 Hyper-v.

I am constantly rebooting servers on a daily basis due to this memory leak with QUIC, unless I disable QUIC on the more busy IIS websites.

**Comment by thhous-msft** [comment] 2022-05-09 17:15
What exactly are the NICs you both are using? Maybe we can get access to a similar system and try some instrumented builds. We have not been able to reproduce this issue so far, and the logs don't really have any information that could point us in the right direction.

Also @Nuklon do you have links to those Reddit posts? I'd be curious to look into them.

**Comment by webwizuk** [comment] 2022-05-10 06:44
I am using SuperMIcro X11SSH+LN4F motherboards which have built-in Intel I210-AT NICs.

The issue does not happen all the time. It tends to occur more frequently on busier Windows Server 2022 IIS web servers, with the issue sometimes occurring after an hour and other times weeks.

If I disable QUIC in the IIS binding for websites that get over 100 concurrent connections it can reduce or stop the "Qc1A Nonp" memory leak occurring with QUIC. These websites can be ASP.NET, Classic ASP or PHP. When it occurs the memory leak will use over 95% of the available physical memory in a few seconds and as it is non-paged pool memory that is used the server has to be rebooted to release the memory.

All the servers are running as virtual machines on Windows Server 2019 Hyper-V using a virtual NIC (not legacy) in the virtual server settings.  The I210-AT NICs are configured using Windows Teaming before being added as Virtual Switches. I have had the problem since Windows Server 2022 was released in August 2021 so seems unrelated to any new Intel drivers.

The servers are configured with HTTP/3 support for IIS enabled as per the instructions at the link below;

https://techcommunity.microsoft.com/t5/networking-blog/enabling-http-3-support-on-windows-server-2022/ba-p/2676880

I also wondered if it was the cypher suits or their order that is unusual and therefore causing the problem. I used IIS Crypto to put the cypher suites in the following order and only have TLS 1.2 and 1.3 enabled.

![image](https://user-images.githubusercontent.com/105198427/167561790-a394a3d5-2e74-4be8-8b82-4370714914c2.png)

I hope that this is helpful to replicate the issue.

**Comment by Nuklon** [comment] 2022-05-10 11:24
> What exactly are the NICs you both are using? Maybe we can get access to a similar system and try some instrumented builds. We have not been able to reproduce this issue so far, and the logs don't really have any information that could point us in the right direction.
> 
> Also @Nuklon do you have links to those Reddit posts? I'd be curious to look into them.

On my servers: Intel i210 integrated NIC. 

The reddit posts about the 13.x drivers are here:
https://www.reddit.com/r/intel/comments/svr2qa/what_is_the_latest_intelr_i211_gigabit_network/
There are more reports on some other forums about these 13.x drivers, such as win-raid here:
https://www.win-raid.com/t7057f42-Latest-Intel-Ethernet-LAN-Drivers-3.html

I have disabled Legacy TLS in IIS as well (not used IIS Crypto), although I doubt that'll be the cause. I've tried to reproduce it on my local machine with Realtek NIC and while I do see some movement to Qc1A, it's not similar as on server as it's just local test traffic. As with @webwizuk, I've not found any logic in how this happens, sometimes the server runs fine for several hours, and then suddenly a big increase of RAM. If I disable QUIC in IIS there's not an issue anymore.

**Comment by Nuklon** [comment] 2023-01-24 12:08
Just tried it again to see if any OS updates have fixed it, but it's unfortunately still happening.

**Comment by nibanks** [comment] 2023-01-24 12:34
@nuklon & @webwizuk thanks for trying again and thank you for your patients. We're actively working on backporting v2.1 MsQuic to WS2022, which should fix all these problems, as well as bring a host of other fixes.

The tentative date is looking to be March for this to ship publically.

**Comment by webwizuk** [comment] 2023-01-24 12:41
That is great news, and thanks for the update.

**Closed** 2023-03-15 13:11 UTC
Labels: Bug: Core, external

**Comment by webwizuk** [comment] 2023-03-15 13:21
Thanks, Nick. I have re-enabled QUIC on my IIS web servers.

I will let you know what happens.

**Comment by nibanks** [comment] 2023-03-15 13:23
> Thanks, Nick. I have re-enabled QUIC on my IIS web servers.
> 
> I will let you know what happens.

Great. Can you confirm that MsQuic is version 2.1 if you look at the properties of `C:\Windows\System32\drivers\msquic.sys`?

**Comment by Nuklon** [comment] 2023-03-15 15:56
I've updated around 7 PM (GMT+1) yesterday, enabled quic again in IIS, and it's been running without issues on v2.1.6.0 since then. It never managed to hold this long with 1.x.

Qc06 has most memory, but doesn't really grow further. Yesterday evening late it was 41... instead of 46...
![image](https://user-images.githubusercontent.com/23340481/225365564-a13ffff9-f25d-45e3-90d9-bda29a3e3097.png)

 I'll keep monitoring it for a couple of days.

**Comment by nibanks** [comment] 2023-03-18 20:42
@Nuklon & @webwizuk just checking in to see if everything is going well for you. Any issues?

**Comment by Nuklon** [comment] 2023-03-19 13:00
Thanks, all is still working well! 🎉

![image](https://user-images.githubusercontent.com/23340481/226176411-13a9a0c9-9c4d-4852-b101-16f137d10c76.png)

Qc06 is now also consistent, I've once seen it at 5.2MB but it quickly freed it up to 4.6MB again, so that indeed seems to be working correctly.
